// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY58-Mir1GVCAQPOIbT8YzeqxZ0xScv3I',
    appId: '1:128052699444:web:7377f5787b204f48f2c561',
    messagingSenderId: '128052699444',
    projectId: 'space-exploration-csc315',
    authDomain: 'space-exploration-csc315.firebaseapp.com',
    storageBucket: 'space-exploration-csc315.firebasestorage.app',
    measurementId: 'G-LR5XB4X46S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJZstwmvdbT1w7yc6d4g-FzU7fLM8DbE',
    appId: '1:128052699444:android:dd802ef07b6e395ef2c561',
    messagingSenderId: '128052699444',
    projectId: 'space-exploration-csc315',
    storageBucket: 'space-exploration-csc315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_TMqySlVQJVdKymP_nMjKVLVL4gDPg4',
    appId: '1:128052699444:ios:8575f88aeaa95119f2c561',
    messagingSenderId: '128052699444',
    projectId: 'space-exploration-csc315',
    storageBucket: 'space-exploration-csc315.firebasestorage.app',
    iosBundleId: 'com.example.spaceExploration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx_TMqySlVQJVdKymP_nMjKVLVL4gDPg4',
    appId: '1:128052699444:ios:8575f88aeaa95119f2c561',
    messagingSenderId: '128052699444',
    projectId: 'space-exploration-csc315',
    storageBucket: 'space-exploration-csc315.firebasestorage.app',
    iosBundleId: 'com.example.spaceExploration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY58-Mir1GVCAQPOIbT8YzeqxZ0xScv3I',
    appId: '1:128052699444:web:d62103fe8cf03443f2c561',
    messagingSenderId: '128052699444',
    projectId: 'space-exploration-csc315',
    authDomain: 'space-exploration-csc315.firebaseapp.com',
    storageBucket: 'space-exploration-csc315.firebasestorage.app',
    measurementId: 'G-BMGJ61CSXF',
  );
}
